Update apply.yaml

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -1,8 +1,15 @@
-name: Terraform Apply
+name: Terraform Apply and Destroy
 
 on:
   workflow_dispatch:
     inputs:
+      action:
+        description: Choose action
+        required: true
+        default: 'apply'
+        options:
+          - apply
+          - destroy
       environment_choice:
         type: choice
         required: true
@@ -23,7 +30,7 @@ on:
           - azure-loadbalancer
 
 jobs:
-  deploy:
+  terraform:
     runs-on: ubuntu-latest
     env:
       ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -31,10 +38,10 @@ jobs:
       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       TF_VERSION: 'latest'
-
+      
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
@@ -73,10 +80,23 @@ jobs:
         run: terraform validate
         working-directory: ${{ steps.set_env.outputs.WORKING_DIRECTORY }}
 
-      - name: Generate Terraform Plan
+      - name: Terraform Plan
         run: terraform plan -var-file="./${{ steps.set_env.outputs.CONFIG_FILE }}" -lock=false
         working-directory: ${{ steps.set_env.outputs.WORKING_DIRECTORY }}
 
-      - name: Apply Terraform Changes
-        run: terraform apply -var-file="./${{ steps.set_env.outputs.CONFIG_FILE }}" -lock=false -auto-approve
+      - name: Apply or Destroy Terraform
+        run: |
+          action=${{ github.event.inputs.action }}
+          config_file="${{ steps.set_env.outputs.CONFIG_FILE }}"
+          working_directory="${{ steps.set_env.outputs.WORKING_DIRECTORY }}"
+          
+          if [ "$action" == "apply" ]; then
+            terraform apply -var-file="./${config_file}" -lock=false -auto-approve
+          elif [ "$action" == "destroy" ]; then
+            terraform destroy -var-file="./${config_file}" -lock=false -auto-approve
+          else
+            echo "Invalid action specified"
+            exit 1
+          fi
         working-directory: ${{ steps.set_env.outputs.WORKING_DIRECTORY }}
+
